[package]
name = "common"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
serde = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }
blake3 = { version = "1.8.3", optional = true }

[features]
default = []
rusqlite = ["dep:rusqlite", "dep:blake3"]
serialization = ["dep:serde"]
